### ISSUE TITLE
pip install logai - Installation step failing

### ISSUE THREAD

**Issue by imaxxs** [salesforce/logai#49]
➜  logai git:(main) python3 -m venv venv
➜  logai git:(main) source venv/bin/activate
(venv) ➜  logai git:(main) pip install logai
Collecting logai
  Downloading logai-0.1.5-py2.py3-none-any.whl (138 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.9/138.9 kB 2.3 MB/s eta 0:00:00
Collecting schema>=0.7.5
  Downloading schema-0.7.5-py2.py3-none-any.whl (17 kB)
Collecting salesforce-merlion>=1.0.0
  Downloading salesforce_merlion-2.0.2-py3-none-any.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 9.8 MB/s eta 0:00:00
Collecting Cython>=0.29.30
  Using cached Cython-0.29.34-py2.py3-none-any.whl (988 kB)
Collecting nltk>=3.6.5
  Downloading nltk-3.8.1-py3-none-any.whl (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 19.8 MB/s eta 0:00:00
Collecting gensim>=4.1.2
  Downloading gensim-4.3.1-cp311-cp311-macosx_10_9_x86_64.whl (24.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.0/24.0 MB 13.4 MB/s eta 0:00:00
Collecting scikit-learn>=1.0.1
  Using cached scikit_learn-1.2.2-cp311-cp311-macosx_10_9_x86_64.whl (9.0 MB)
Collecting pandas>=1.2.0
  Using cached pandas-2.0.0-cp311-cp311-macosx_10_9_x86_64.whl (11.6 MB)
Collecting numpy>=1.21.4
  Using cached numpy-1.24.2-cp311-cp311-macosx_10_9_x86_64.whl (19.8 MB)
Collecting spacy>=3.2.2
  Downloading spacy-3.5.2-cp311-cp311-macosx_10_9_x86_64.whl (6.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 25.0 MB/s eta 0:00:00
Collecting attrs>=21.2.0
  Downloading attrs-23.1.0-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 2.2 MB/s eta 0:00:00
Collecting dataclasses>=0.6
  Downloading dataclasses-0.6-py3-none-any.whl (14 kB)
Collecting PyYAML>=6.0
  Using cached PyYAML-6.0-cp311-cp311-macosx_10_9_x86_64.whl (188 kB)
Collecting tqdm>=4.62.3
  Using cached tqdm-4.65.0-py3-none-any.whl (77 kB)
Collecting cachetools>=4.2.4
  Using cached cachetools-5.3.0-py3-none-any.whl (9.3 kB)
Collecting matplotlib>=3.5.1
  Using cached matplotlib-3.7.1-cp311-cp311-macosx_10_12_x86_64.whl (7.4 MB)
Collecting seaborn>=0.11.2
  Downloading seaborn-0.12.2-py3-none-any.whl (293 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 293.3/293.3 kB 10.1 MB/s eta 0:00:00
Collecting Jinja2>=3.0.0
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB 4.7 MB/s eta 0:00:00
Collecting numba>=0.56.3
  Downloading numba-0.56.4.tar.gz (2.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 22.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/lv/dp0pdtvx7hn2j57c6drjx2v40000gn/T/pip-install-xzwkvlzr/numba_ecd71d2111374a099c66633fb9a0b4dc/setup.py", line 51, in <module>
          _guard_py_ver()
        File "/private/var/folders/lv/dp0pdtvx7hn2j57c6drjx2v40000gn/T/pip-install-xzwkvlzr/numba_ecd71d2111374a099c66633fb9a0b4dc/setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.2; only versions >=3.7,<3.11 are supported.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip available: 22.3.1 -> 23.1
[notice] To update, run: pip install --upgrade pip

**Comment by imaxxs** [comment]
It looks like numba package installation is failing during logai installation.

**Comment by imaxxs** [comment]
Any ideas on how to fix this?

**Comment by alanhe** [comment]
I get the same errors for having python 3.11.2.

I install an older python `brew install python@3.10` and then use it create the virtual env:

```
python3.10 -m venv venv

source venv/bin/activate

pip install ".[dev]"
pip install ".[gui]"
pip install ".[deep-learning]"

export PYTHONPATH='.'
python3 gui/application.py
```

See no error so far.
