### ISSUE TITLE
Error during logai install command - Getting requirements to build wheel ... error ;  error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by Tixi3** [salesforce/logai#80]
I want to run Logai locally via VSCode. I positioned myself to logai folder, set up the environment and when I try "pip3 install logai" command, I receive the following error. 
I tried to solve it with following commands: pip3 install --upgrade pip setuptools wheel Cython
pip3 install --no-build-isolation logai
pip3 install --no-cache-dir logai
pip3 install --no-build-isolation logai
pip3 install --prefer-binary logai
and nothing worked, I always receive the same error.

This is the error:
Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [67 lines of output]
      <string>:19: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      <string>:53: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
      <string>:56: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
      <string>:53: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
     
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      cimport cython
      cimport numpy as np
      import numpy as np
     
      ctypedef np.float64_t DOUBLE
      ctypedef np.int_t INT
               ^
      ------------------------------------------------------------
     
      statsmodels\nonparametric\linbin.pyx:13:9: 'int_t' is not a type identifier
      Compiling statsmodels/tsa/_stl.pyx because it changed.
      Compiling statsmodels/tsa/holtwinters/_exponential_smoothers.pyx because it changed.
      Compiling statsmodels/tsa/exponential_smoothing/_ets_smooth.pyx because it changed.
      Compiling statsmodels/tsa/_innovations.pyx because it changed.
      Compiling statsmodels/tsa/regime_switching/_hamilton_filter.pyx because it changed.
      Compiling statsmodels/tsa/regime_switching/_kim_smoother.pyx because it changed.
      Compiling statsmodels/tsa/innovations/_arma_innovations.pyx because it changed.
      Compiling statsmodels/nonparametric/linbin.pyx because it changed.
      Compiling statsmodels/robust/_qn.pyx because it changed.
      Compiling statsmodels/nonparametric/_smoothers_lowess.pyx because it changed.
      Compiling statsmodels/tsa/statespace/_initialization.pyx because it changed.
      Compiling statsmodels/tsa/statespace/_representation.pyx because it changed.
      Compiling statsmodels/tsa/statespace/_kalman_filter.pyx because it changed.
      Compiling statsmodels/tsa/statespace/_filters/_conventional.pyx because it changed.
      Compiling statsmodels/tsa/statespace/_filters/_inversions.pyx because it changed.
      Compiling statsmodels/tsa/statespace/_filters/_univariate.pyx because it changed.
      Compiling statsmodels/tsa/statespace/_filters/_univariate_diffuse.pyx because it changed.
      Compiling statsmodels/tsa/statespace/_kalman_smoother.pyx because it changed.
      Compiling statsmodels/tsa/statespace/_smoothers/_alternative.pyx because it changed.
      Compiling statsmodels/tsa/statespace/_smoothers/_classical.pyx because it changed.
      Compiling statsmodels/tsa/statespace/_smoothers/_conventional.pyx because it changed.
      Compiling statsmodels/tsa/statespace/_smoothers/_univariate.pyx because it changed.
      Compiling statsmodels/tsa/statespace/_smoothers/_univariate_diffuse.pyx because it changed.
      Compiling statsmodels/tsa/statespace/_simulation_smoother.pyx because it changed.
      Compiling statsmodels/tsa/statespace/_cfa_simulation_smoother.pyx because it changed.
      Compiling statsmodels/tsa/statespace/_tools.pyx because it changed.
      [ 1/26] Cythonizing statsmodels/nonparametric/_smoothers_lowess.pyx
      [ 2/26] Cythonizing statsmodels/nonparametric/linbin.pyx
      Traceback (most recent call last):
        File "C:\Users\uie44461\develop\AI_tools\logai\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\uie44461\develop\AI_tools\logai\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\uie44461\develop\AI_tools\logai\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\uie44461\AppData\Local\Temp\pip-build-env-auutofc1\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel     
          return self._get_build_requires(config_settings, requirements=[])
        File "C:\Users\uie44461\AppData\Local\Temp\pip-build-env-auutofc1\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "C:\Users\uie44461\AppData\Local\Temp\pip-build-env-auutofc1\overlay\Lib\site-packages\setuptools\build_meta.py", line 516, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\uie44461\AppData\Local\Temp\pip-build-env-auutofc1\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 304, in <module>
        File "C:\Users\uie44461\AppData\Local\Temp\pip-build-env-auutofc1\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "C:\Users\uie44461\AppData\Local\Temp\pip-build-env-auutofc1\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: statsmodels/nonparametric/linbin.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by aandino** [comment]
Hi, we had been the same problem.
It was solutioned using python version 3.9.20 using pyenv.

**Comment by DatadudeDev** [comment]
pip install logai in a fresh venv yeilds a flurry of errors. I found that uninstalling statsmodels, numpy, and scipy then defining explicit versions in a constraints.txt did the trick.

contents of ./constraints.txt:

numpy==1.23.5
cython==0.29.36
scipy==1.10.1
statsmodels==0.14.2

run the installation with this command:

pip install --no-cache-dir --constraint constraints.txt logai

**Comment by Tixi3** [comment]
> Hi, we had been the same problem. It was solutioned using python version 3.9.20 using pyenv.

Thank you for your help! It seems that we need to use specified version of python.

**Comment by Tixi3** [comment]
> pip install logai in a fresh venv yeilds a flurry of errors. I found that uninstalling statsmodels, numpy, and scipy then defining explicit versions in a constraints.txt did the trick.
> 
> contents of ./constraints.txt:
> 
> numpy==1.23.5 cython==0.29.36 scipy==1.10.1 statsmodels==0.14.2
> 
> run the installation with this command:
> 
> pip install --no-cache-dir --constraint constraints.txt logai

Thank you for your help! And which python version were you using?

**Comment by DatadudeDev** [comment]
Some better instructions to getting the server running. 

1. Clone the repo
2. wget Python3.9.20 tarball and extract inside the cloned repo directory

https://www.python.org/ftp/python/3.9.20/Python-3.9.20.tgz

```
./logai
├── requirements.txt
├── Python3.9.20
    └── env
```


3.` chown -R  /logai `to grant permissions

4. create a ./constraints.txt and add the following contents: 
```
numpy==1.23.5
cython==0.29.36
scipy==1.10.1
statsmodels==0.14.2
```
5. create and activate a python venv inside the Python3.9.20 directory

` (./logai/Python3.9.20/env/bin/activate)
`

6. export the new python path: 

`export PATH="/home/king/logai/Python-3.9.20/env/bin:$PATH"
`

7. confirm python version with: 

`which python`

8. install with: 
`pip install --no-cache-dir --constraint constraints.txt logai['All]
`

9: Update the classes accordingly in logai/dataloader/data_model.py.

```
class LogRecordObject:
timestamp: pd.DataFrame = field(default_factory=pd.DataFrame)
attributes: pd.DataFrame = field(default_factory=pd.DataFrame)
resource: pd.DataFrame = field(default_factory=pd.DataFrame)
trace_id: pd.DataFrame = field(default_factory=pd.DataFrame)
span_id: pd.DataFrame = field(default_factory=pd.DataFrame)
severity_text: pd.DataFrame = field(default_factory=pd.DataFrame)
severity_number: pd.DataFrame = field(default_factory=pd.DataFrame)
body: pd.DataFrame = field(default_factory=pd.DataFrame)
labels: pd.DataFrame = field(default_factory=pd.DataFrame)
_index: np.array = field(init=False)
```

9b (optional): if not running locally, update ./gui/application.gui to run on 0.0.0.0

`if __name__ == "__main__":
    app.run_server(debug=False, host='0.0.0.0')`

10. cd into root logai directory and run to start the server: 

`python -m gui.application`



**EDIT**: Confirming these steps work to produce a working server and output good data, see attached. 

![image](https://github.com/user-attachments/assets/500d1052-02d9-466c-9cc9-b78574a697d2)
![image](https://github.com/user-attachments/assets/bdce6822-c09f-4b03-8f13-f3f5d23d5450)



I've exported the precompiled project and mirrored it this repo. Simply clone, activate the venv , set your Python PATH and run the application. if you want your own venv, create one within the Python3.9.20 directory and run

>>> https://github.com/DatadudeDev/logai <<<

`pip install -r requirements.txt`  <-- derived from my working environment with `pip freeze`


**I'm a new dev and this is one of my first contributions to a codebase so some stars would be crazy appreciated**

**Comment by Tixi3** [comment]
Thank you very much!
